### ISSUE TITLE
twrp E: unknown filesystem 'sdfat'

### ISSUE THREAD

**Issue by fractal1510** [DeadSquirrel01/lineage-16_a5_releases#11]
That's the error i get and i thought that twrp is missing vfat support, but closer inspection of /etc/twrp.fstab shows that external_sd fs type is sdfat?? Is that typo or should it say vfat or something?

**Comment by DeadSquirrel01** [comment]
Oh, I've just noticed that the repo has a twrp.fstab that has "sdfat" instead of "auto", that's where the problem comes from. Next build will contain the fix for that

**Comment by DeadSquirrel01** [comment]
Fixed in 20181102 release
