### ISSUE TITLE
Phone echo issue

### ISSUE THREAD

**Issue by dividebynone** [DeadSquirrel01/lineage-16_a5_releases#12]
I've been having this issue with both LineageOS 15.1 and now 16 and I can't seem to find a solution. People on the other side of the call hear an echo of their own voice. From what I have read, it seems to be a rather common issue when it comes to custom ROMs. I tried modifying the build.prop according to the suggested solutions but unfortunately that did not fix it.. 

**audio_platform_info.xml** also seems to be completely missing from the device.

**Comment by DeadSquirrel01** [comment]
Have you tried excluding things like rooms that cause echo, trying in stock rom, etc?
Also we don't need audio_platform_info.xml since we are using stock audio HAL, that's why it's missing

**Comment by dividebynone** [comment]
Sorry for the late response. I reverted back to the stock ROM which seems to have solved the echo issue. I guess I'll be staying with Android Marshmallow unless you manage to find some sort of solution.

I have no idea what caused the echo and probably never will. I guess it might have something to do with the region,carrier or a microphone issue caused by LineageOS but those are just speculations.

**Comment by DeadSquirrel01** [comment]
Closing, please reopen if you want to say something else about this
