### ISSUE TITLE
battery life not so well

### ISSUE THREAD

**Issue by destroyerbd** [DeadSquirrel01/lineage-16_a5_releases#13]
battery life very bad

**Comment by DeadSquirrel01** [comment]
This is 9.0 not 4.4. Try to find ways to improve battery life with google

**Comment by destroyerbd** [comment]
> This is 9.0 not 4.4. Try to find ways to improve battery life with google

battery so  match drain bro

**Comment by destroyerbd** [comment]
> I've already told you what to do. If you want better battery life use an older version of android or buy a new phone with a better battery. Disabling some things will enhance battery life, but as i said, 9.0 is not 4.4. Google makes heavier oses every year. That's normal for example windows xp uses more ram, cpu... than windows 10, in android it's the same. That's it. And in my rom there aren't such big bugs that cause overload.

tnx for replay ..............tnx for development a500fu model..............................................tnx a lot ......................

**Comment by destroyerbd** [comment]
> bu

plz i m using a500h model also duel sim . my a500fu model phone android 9 work fine but your android pie rom not supported on sm-a500h model ................................can u try to add malti support mains a5 all variant support ur android pie rom . i know it easy to build rom for other variant but all user not a >> dev <<   i know also u dont have time to build rom for other variant  but if u try it possible to support rom for a5 all variant ur android pie rom  tnx for developted a beautiful rom.

**Comment by DeadSquirrel01** [comment]
No, it's clearly written in the README.
Closing..
