### ISSUE TITLE
Google Pixel Launcher hangs while pressing home button

### ISSUE THREAD

**Issue by luanfsp** [DeadSquirrel01/lineage-16_a5_releases#17]
Sorry by my english. I'm brazilian.

Model: SM-A500M. Last rom update.

After installing the stock gapps and configuring the device, the Google Pixel Launcher hangs when you press the home button. The rest works perfectly well. In addition I would like to thank all the participants for bringing good roms to the Brazilians. You guys did a great job.

**Comment by DeadSquirrel01** [comment]
Lineageos has trebuchet launcher. You can install any launcher you want but I won't support it as I don't support third-party apps (obviously!).
Closing
