### ISSUE TITLE
phone shuts down 

### ISSUE THREAD

**Issue by mauriciorv97** [DeadSquirrel01/lineage-16_a5_releases#19]
I had a previous version of unofficial LOS which was 14.1. I did as it says on the instructions here on this page. Wiped system data dalvik and cache, flashed the rom then ril and then gapps (downloaded from the official open gapps project) armv version android 9 pico package. So it flashes fine the phone starts (it takes like 2 minutes, no more) and I start setting things up and all of a sudden the phone ust turns off, I mean screen goes black not even the shutting down warning on screen appears, it just turns off. I have flashed many times the rom whit the gapps, whitout the gapps, with ril, whitout ril (even if I don't flash the ril all connectivities options work) and it still happens. What else can I do?

**Comment by Alex01d** [comment]
I have the same problem on A500F. And looks like the phone gets hot.

**Comment by mauriciorv97** [comment]
yes sir, thats exactly what happens. I found out that it happens when the phone heats up. But I have been using the rom for 3 days now and It hasn't happened anymore. hope this doesn't happen again.

PS: so I will leave this post open for a couple of days more to check things are going well so then I'll close it

**Comment by Alex01d** [comment]
Just tested my phone with AnTuTu stress tests: when the proccessor reaches 80°C, the phone shuts down.

**Comment by mauriciorv97** [comment]
Thankyou for the info sir. 
But, well, in a normal use (games, social media, photos, etc) There's no problem, I noticed that the problem was when installing the rom which gets the phone very hot ans so then it occurs the shut down. 
Anyway I've had the rom installed for days now and works 10/10 There is just another "problem" concerning the sound of some tones but I'll open another post (hopping the developer reads it and fixs it)

**Comment by virtuacool** [comment]
I have a SM-500FU and had not yet any problems of these.
In my case, it has worked beautifully!

**Comment by DeadSquirrel01** [comment]
I need a logcat

**Comment by Alex01d** [comment]
@DeadSquirrel01 
[logcat.txt](https://github.com/DeadSquirrel01/lineage-16_a5_releases/files/3005705/logcat.txt)
The problem is logged in last 2 lines.

**Comment by DeadSquirrel01** [comment]
So, the cpu reached 97 °C and thermal-engine shuted you phone down for security reasons. You can disable it by adding a "disabled" line (without "") in thermal-engine service in /system/vendor/etc/init/hw/init.qcom.rc

**Comment by Alex01d** [comment]
Just passed AnTuTu stress test with the new config. No overheating. Perfect, thanks!

**Comment by pardorulez97** [comment]
Where can i edit that file? in recovery twrp?

**Comment by Alex01d** [comment]
If your phone is rooted, allow root access for adb in developer settings, then connect to it via ADB shell and run these commands:
1) `mount -o rw,remount /system` (to make the system partition writable)
2) `cat > /system/vendor/etc/thermal-engine.conf` (then press enter, paste contents from https://pastebin.com/UHLffmbE, the raw version, and press Ctrl+D)
3) `mount -o ro,remount /system` (to make the system partition read-only again)
Then check the config file by running `cat /system/vendor/etc/thermal-engine.conf` and reboot.

**Comment by mauriciorv97** [comment]
nice you ansewered sir,  
But since I'm a not developer nor have knowledge of programming I'd rather leave it like that, anyway the only time it has happened was when I first installed the rom which make the temperature go very high. But now it works perfectly fine. So now I can close this post. 

BTW: Very nice work on making this rom sir. I follow u since you made the lineage rom 14.1, sadly that one didn't work on SM-A500M

**Comment by pardorulez97** [comment]
> If your phone is rooted, allow root access for adb in developer settings, then connect to it via ADB shell and run these commands:
> 
> 1. `mount -o rw,remount /system` (to make the system partition writable)
> 2. `cat > /system/vendor/etc/thermal-engine.conf` (then press enter, paste contents from https://pastebin.com/UHLffmbE, the raw version, and press Ctrl+D)
> 3. `mount -o ro,remount /system` (to make the system partition read-only again)
>    Then check the config file by running `cat /system/vendor/etc/thermal-engine.conf` and reboot.

thanx Alex, let me try it

**Comment by pardorulez97** [comment]
> If your phone is rooted, allow root access for adb in developer settings, then connect to it via ADB shell and run these commands:
> 
> 1. `mount -o rw,remount /system` (to make the system partition writable)
> 2. `cat > /system/vendor/etc/thermal-engine.conf` (then press enter, paste contents from https://pastebin.com/UHLffmbE, the raw version, and press Ctrl+D)
> 3. `mount -o ro,remount /system` (to make the system partition read-only again)
>    Then check the config file by running `cat /system/vendor/etc/thermal-engine.conf` and reboot.

I didn't find it in that route the file

**Comment by Alex01d** [comment]
Did you do it as root? Use `su -` command to become root.

**Comment by pardorulez97** [comment]
> Did you do it as root? Use `su -` command to become root.

yes i did it as root

**Comment by pardorulez97** [comment]
> Did you do it as root? Use `su -` command to become root.

Its done and its working fine with the gapps, no shutdown =)
