### ISSUE TITLE
Sim card not detected on A500m/ds

### ISSUE THREAD

**Issue by Logicau** [DeadSquirrel01/lineage-16_a5_releases#20]
i flashed the rom and sim card not appears in configurations

**Comment by mauriciorv97** [comment]
have you flashed the ril file sir?

**Comment by Logicau** [comment]
Yes I flashed the ril fix, and  after a while works fine. I was wrong to think was not working. :)

**Comment by Logicau** [comment]
Yes I flashed the ril fix, and  after a while works fine. I was wrong to think was not working. :)
