### ISSUE TITLE
which gapps version ARM or AMR64?

### ISSUE THREAD

**Issue by sopos** [DeadSquirrel01/lineage-16_a5_releases#21]
ssia

**Comment by sopos** [comment]
ok, the answer is ARM, it would be better to explicitly write it to the README than letting users download both and try.

**Comment by virtuacool** [comment]
I used the Open Gapps (micro) ARM version, and it worked perfectly.
The ARM64 version does not work on this model.
https://opengapps.org/?api=9.0&variant=micro

**Comment by DeadSquirrel01** [comment]
Users can easily find out on google, i dont think that would be so hard to find such an easy information.
Closing
