### ISSUE TITLE
touch and buttons stop working after latest update

### ISSUE THREAD

**Issue by mauriciorv97** [DeadSquirrel01/lineage-16_a5_releases#25]
I have just installed the latest update lineageos 16.0 20190328 and when I turn on the screen the touch doesn't work or goes laggy, I have tu turn off and on a lot of times to get it working correctly also back and menu buttons stop working (home button works fine).  This started happening after latest update.

**Comment by y0lopix** [comment]
I have the same problem since 20190328. Sometimes when turning on the screen, it becomes unresponsive or the screen touches itself. I had the same bug on some builds of LineageOS 14.1.
Also, the soft buttons light up and vibrates by themselves randomly or they just stop working. They also continue to vibrate when touching them even when the screen is locked. I haven't encountered most of these bugs in 20190225

**Comment by DeadSquirrel01** [comment]
I have to fix a couple of selinux denials. I will do it as soon as possible. stay tuned

**Comment by mauriciorv97** [comment]
> I have to fix a couple of selinux denials. I will do it as soon as possible. stay tuned



> I have the same problem since 20190328. Sometimes when turning on the screen, it becomes unresponsive or the screen touches itself. I had the same bug on some builds of LineageOS 14.1.
> Also, the soft buttons light up and vibrate by themselves randomly or they just stop working. They also continue to vibrate when touching them even when the screen is locked. I haven't encountered most of these bugs in 20190225

yeah and it gets so annoying to the point I have to reboot the phone every time the physical buttons stop working at all. But I'm pretty sure the guy who created the rom will fix it.

**Comment by mauriciorv97** [comment]
> I have to fix a couple of selinux denials. I will do it as soon as possible. stay tuned

oh thankyou sir you've done an awesome job with this rom,
I don't know if you have read my other post about the problems with t he sounds, I would appreciate it if you could also fix this on upcoming releases. 

Have a good day

**Comment by maheen1234** [comment]
> > I have to fix a couple of selinux denials. I will do it as soon as possible. stay tuned
> 
> oh thankyou sir you've done an awesome job with this rom,
> I don't know if you have read my other post about the problems with t he sounds, I would appreciate it if you could also fix this on upcoming releases.
> 
> Have a good day

brother you are talking about the audio video sync issue im also facing the same problem. i watch some videos on youtube related to this issue they said wipe your cache in twrp i did that and the problem gone. but after some time the issue comes again. i google google google about this issue but can't find any solution.

**Comment by mauriciorv97** [comment]
> > > I have to fix a couple of selinux denials. I will do it as soon as possible. stay tuned
> > 
> > 
> > oh thankyou sir you've done an awesome job with this rom,
> > I don't know if you have read my other post about the problems with t he sounds, I would appreciate it if you could also fix this on upcoming releases.
> > Have a good day
> 
> brother you are talking about the audio video sync issue im also facing the same problem. i watch some videos on youtube related to this issue they said wipe your cache in twrp i did that and the problem gone. but after some time the issue comes again. i google google google about this issue but can't find any solution.

audio video sync?  no, not at all dude. What I'm talking abaout is that for example I set the volumme for my ringtone in the lowest level and it sounds like if it was set with the highest level, so you can imagine what a noise It makes if I turn the volumme uo just a bit for my ringtone, same happens with the alarm and notification sound

**Comment by maheen1234** [comment]
> > > > I have to fix a couple of selinux denials. I will do it as soon as possible. stay tuned
> > > 
> > > 
> > > oh thankyou sir you've done an awesome job with this rom,
> > > I don't know if you have read my other post about the problems with t he sounds, I would appreciate it if you could also fix this on upcoming releases.
> > > Have a good day
> > 
> > 
> > brother you are talking about the audio video sync issue im also facing the same problem. i watch some videos on youtube related to this issue they said wipe your cache in twrp i did that and the problem gone. but after some time the issue comes again. i google google google about this issue but can't find any solution.
> 
> audio video sync? no, not at all dude. What I'm talking abaout is that for example I set the volumme for my ringtone in the lowest level and it sounds like if it was set with the highest level, so you can imagine what a noise It makes if I turn the volumme uo just a bit for my ringtone, same happens with the alarm and notification sound

oh i see thats the problem you are facing. but im not facing this problem im facing audio video sync issue but now its resolved automatically Thank God. im using A500f variant and im not dude im a girl :-)

**Comment by mauriciorv97** [comment]
oh sorry miss :D nice to know. 
Well since the developer of this rom don't release any update fixing this I had to go back on the previous version to fix the problem. (The heat problem is controllable anyways so ...) 
Hope a new version is released soon

**Comment by DeadSquirrel01** [comment]
I'll upload a new release when i have time. Now i dont have time although i've already fixed it on my pc

**Comment by maheen1234** [comment]
> I'll upload a new release when i have time. Now i dont have time although i've already fixed it on my pc

no problem. you already did alot of work just for us for free. its too hard to share work with someone without any money. you giving our old phone's a new life. thanks for all the work that you have done for us. thank you very much.

**Comment by wagnerflo** [comment]
Same problem here. Looking forward to a release with the fix included. Thank you! :)

**Comment by DeadSquirrel01** [comment]
fixed in 7th release
