### ISSUE TITLE
Netflix doesn't work it says device is incompatible and liboemcrypto magisk module not working.

### ISSUE THREAD

**Issue by aayush0508** [DeadSquirrel01/lineage-16_a5_releases#26]
Title says it all

**Comment by DeadSquirrel01** [comment]
Probably netflix just don't want to support custom roms. You can accept it or find other ways to use it, but obviously this is not the right place for that, and it's not an issue of this port

**Comment by aayush0508** [comment]
I'm sorry I won't disturb you.
Just that your previous builds of lineage OS didn't have this problem.
So I thought you could fix this.

**Comment by DeadSquirrel01** [comment]
Then can you try to make selinux permissive to see if problem persists?

**Comment by aayush0508** [comment]
How can I do that??
I tried to flash permissive.zip from erfanoabdi
Now the ROM no longer boots.
