### ISSUE TITLE
twrp sdfat support

### ISSUE THREAD

**Issue by fractal1510** [DeadSquirrel01/lineage-16_a5_releases#3]
is it possible to build next twrp with sdfat support, i'm storing rom images on external sd card, also my usb is broken so if something goes wrong, my only option is to sideload images from sd card.

**Comment by DeadSquirrel01** [comment]
Sdfat support has no sense if twrp has exfat. In fact sdfat is used as a sort of exfat replacement, so, you can can manage vfat partition if you have sdfat or exfat. Therefore, the current twrp which has exfat driver is able to mount/unmount and manage vfat partitions that in lineage are mounted with sdfat.
Closing; reopen if you have something to add
