### ISSUE TITLE
Screen goes black during phone calls

### ISSUE THREAD

**Issue by knuxify** [DeadSquirrel01/lineage-16_a5_releases#34]
(TODO: attach logs)
When making a phone call, the screen goes black and the touchscreen doesn't work.

The dialer app is set as default in Settings.

**Comment by DeadSquirrel01** [comment]
mobile phones like a5 have something called "proximity sensor", so, unless it's not covered by your face,fingers et cetera, that's normal

**Comment by knuxify** [comment]
Alright, nevermind, figured it out: I covered my front camera with a sticker and didn't realize I also covered the proximity sensor.
