### ISSUE TITLE
A5000 menu/back button not working (A5LTEZH)

### ISSUE THREAD

**Issue by NSilviaS15** [DeadSquirrel01/lineage-16_a5_releases#36]
The backlight option does nothing, and the buttons do not respond under any circumstances.
I did have to mod the updater-script in META-INF\com\google\android to make it install.
I did delete the entire OS off the phone before installation, so maybe I deleted something I shouldn't...? First time doing TWRP/LineageOS (because I screwed up rooting it) so I am really not sure what went wrong.

Oh, and, um, well, there is no RIL fix applied.

If this is not supported, please also tell me so I can tell myself off.

**Comment by NSilviaS15** [comment]
This is kind of off topic but

Adding that the gyro is f-ed as well.
When holding the phone 
up: X=-9
right side up: Y=+9
Z axis seems to be fine for now but not really sure

**Comment by DeadSquirrel01** [comment]
Yes, it's not supported. It's written in the first line of readme.md in bold that only a500 variants are supported
