### ISSUE TITLE
phone reboots to recovery when /data is f2fs formatted

### ISSUE THREAD

**Issue by fractal1510** [DeadSquirrel01/lineage-16_a5_releases#4]
First boot shows Lineage logo for a while and then reboots to recovery. Formatting /data to ext4 fixes the problem.

**Comment by DeadSquirrel01** [comment]
This rom doesn't support F2FS. Maybe in the future it will, but not now

**Comment by DeadSquirrel01** [comment]
F2FS support has been added in 20181102 release and will be present in future ones
