### ISSUE TITLE
Bluetooth audio issues

### ISSUE THREAD

**Issue by krmax44** [DeadSquirrel01/lineage-16_a5_releases#6]
When I connect my Bluetooth headphones, it doesn't play the audio through it and uses the phones internal speaker. I can however control play/pause using the buttons on the headphones, but not the volume.
Also, it sometimes says "Connecting..." even though it's connected.

**Comment by fractal1510** [comment]
Same problem, only with Bluetooth speakers.

**Comment by DeadSquirrel01** [comment]
Fixed in 5th and newer releases
