### ISSUE TITLE
roomservice.xml

### ISSUE THREAD

**Issue by m4w0lf** [DeadSquirrel01/lineage-16_a5_releases#8]
Hi,
can you please share the roomservice.xml file used for this release?

I'm having some issues writing it myself (build environment breaks very often and even if the building ends with success, the rom doesn't boot successfully and remains stuck)

Thank you and best regards

**Comment by DeadSquirrel01** [comment]
No and this is not an issue about the rom.
Closing...

**Comment by krmax44** [comment]
It would still be nice if you could share it with us. It would allow us to build the ROM ourselves and help making it more stable.
